<a href="https://colab.research.google.com/github/atif4/Q2/blob/gh-pages/Copy_of_numpy_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem  1

Convert a 1D array to a 2D array with 2 rows

Input:
```
np.arange(10)

#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

Output:


```
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])
```



In [ ]:
# Import the NumPy package with the alias 'np'
import numpy as np

# Create a one-dimensional array of 10 elements using the arange function from NumPy and assign it to the variable 'a'
a = np.arange(2*5)

# Display the contents of the array 'a' using the display function
display(a)

# Reshape the array 'a' into a two-dimensional array with 2 rows and 5 columns using the reshape method and display the result
display(a.reshape(2,5))


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Problem  2

Extract all odd numbers from arr

```
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```



In [ ]:
# Create a NumPy array of integers from 0 to 9 and assign it to the variable 'arr'
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Create a new array 'arr_odd' that only contains the odd elements of 'arr'
# This is achieved by selecting the elements of 'arr' where their value modulo 2 is not 0 (i.e., odd numbers)
arr_odd = arr[arr%2!=0]

# Display a message and the contents of the 'arr_odd' array using the display function
display("ODD",arr_odd)

# Create a new array 'arr_even' that only contains the even elements of 'arr'
# This is achieved by selecting the elements of 'arr' where their value modulo 2 is 0 (i.e., even numbers)
arr_even = arr[arr%2==0]

# Display a message and the contents of the 'arr_even' array using the display function
display("EVEN",arr_even)


'ODD'

array([1, 3, 5, 7, 9])

'EVEN'

array([0, 2, 4, 6, 8])

Problem  3

Replace all odd numbers in arr with -1

```
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

Output:


```
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
```



In [ ]:
# Create a NumPy array of integers from 0 to 9 and assign it to the variable 'arr'
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Select the elements of 'arr' where their value modulo 2 is not 0 (i.e., odd numbers)
# Assign the value -1 to those elements, effectively replacing them with -1
arr[arr%2!=0] = -1

# Display the contents of the modified 'arr' array using the display function
display(arr)


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Problem  4

Replace all odd numbers in arr with -1 without changing arr

Input:

`arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])`

Desired Output:

```
out
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr
#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```




In [ ]:
# Create a NumPy array of integers from 0 to 9 and assign it to the variable 'arr'
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Create a copy of the 'arr' array using the copy method of NumPy and assign it to the variable 'copy'
copy = np.copy(arr)

# Select the elements of 'arr' where their value modulo 2 is not 0 (i.e., odd numbers)
# Assign the value -1 to those elements, effectively replacing them with -1
arr[arr%2!=0] = -1

# Display a message and the contents of the modified 'arr' array using the display function
display("output",arr)

# Display a message and the contents of the original 'arr' array using the display function
display("arr",copy)


'output'

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

'arr'

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Problem  5

Stack arrays a and b vertically

Input



```
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```


Desired Output:


```
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
```




In [ ]:
# Create a NumPy array containing integers from 0 to 9 using the arange method and then reshape it into a 2x5 array
a = np.arange(10).reshape(2,-1)

# Create a NumPy array containing ten 1s using the repeat method and then reshape it into a 2x5 array
b = np.repeat(1, 10).reshape(2,-1)

# Display the desired output of vertically stacking the 'a' and 'b' arrays using the vstack method of NumPy
display("Desired Output: vstack",np.vstack((a,b)))


'Desired Output: vstack'

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Problem  6

Stack the arrays a and b horizontally.

Input


```
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```


Desired Output:



```
array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
```




In [ ]:
# Display the desired output of horizontally stacking the 'a' and 'b' arrays using the hstack method of NumPy
display("Desired Output: np.hstack",np.hstack((a,b)))

'Desired Output: np.hstack'

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

Problem  7

Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:



```
a = np.array([1,2,3])
```


Desired Output:



```
#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```




In [ ]:
a = np.array([1,2,3])
#display("a",a)

repeat = np.repeat(a, 3)
#display("np.repeat:",repeat)

"""Numpy tile (np.tile) in Python simply repeats the numbers of elements present in an array. Suppose you have a numpy array [4,5,6,7],
then np.tile([4,5,6,7], 3) will duplicate the elements three times and make a new array."""
tile = np.tile([1, 2, 3], 3)
# display("np.tile",tile)
# np.r_[] concatenates arrays along first axis.
r_ = np.r_[repeat, tile]
display("Desired Output: np.r_",r_)

# np.c_[] concatenates arrays along second axis.
c_ = np.c_[repeat, tile]
#display("np.c_",c_)

'Desired Output: np.r_'

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Problem  8

From array a remove all items present in array b

Input:


```
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
```

Desired Output:

```
array([1,2,3,4])
```




In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
"""Find the set difference of two arrays.
Return the unique values in ar1 that are not in ar2."""
diff_of_a_b = np.setdiff1d(a, b)
display("Desired Output: np.setdiff1d",diff_of_a_b)

'Desired Output: np.setdiff1d'

array([1, 2, 3, 4])

Problem  9

Get the positions where elements of a and b match

Input:



```
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```


Desired Output:



```
(array([1, 3, 5, 7]),)
```



In [ ]:
# Create two NumPy arrays, 'a' and 'b', containing integer values
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# Use the where() method of NumPy to compare the values in 'a' and 'b', and return the indices of where they are equal
indices = np.where(a == b)

# Display the resulting indices as the desired output
display("Desired Output:", indices)


'Desired Output:'

(array([1, 3, 5, 7]),)

Problem  10

Swap columns 1 and 2 in the array arr.

```
arr = np.arange(9).reshape(3,3)
```

Output:



```
array([[1, 0, 2],
      [4, 3, 5],
      [7, 6, 8]])
```




In [ ]:
# Create a NumPy array 'arr' containing integer values and reshape it to a 3x3 array
arr = np.arange(9).reshape(3,3)

# Use NumPy slicing to swap the first and second columns of 'arr', and assign the result to 'swap'
swap = arr[:, [1, 0, 2]]

# Display the resulting array with swapped columns using the display function
display("output swap:", swap)


'output swap:'

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

Problem  11

From the array a, replace all values greater than 30 to 30 and less than 10 to 10.

Input:


```
np.random.seed(100)
a = np.random.uniform(1,50, 20)
```


In [ ]:
# Set the seed for NumPy's random number generator to ensure consistent results
np.random.seed(100)

# Generate a NumPy array 'a' containing 20 random float values between 1 and 50 using the uniform distribution
a = np.random.uniform(1,50, 20)

# Use NumPy indexing to replace any values in 'a' that are greater than or equal to 30 with the value 30
a[a >= 30] = 30

# Use NumPy indexing to replace any values in 'a' that are less than or equal to 10 with the value 10
a[a <= 10] = 10

# Display the resulting array 'a' using the display function
display("a",a)


'a'

array([27.62684215, 14.64009987, 21.80136195, 30.        , 10.        ,
       10.        , 30.        , 30.        , 10.        , 29.17957314,
       30.        , 11.25090398, 10.08108276, 10.        , 11.76517714,
       30.        , 30.        , 10.        , 30.        , 14.42961361])

Problem  12

Compute the counts of unique values row-wise.

Input:



```
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr
> array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
>        [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
>        [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
>        [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
>        [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
>        [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])
```



Desired Output:



```
> [[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
>  [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
>  [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
>  [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
>  [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
>  [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]
```



In [ ]:
# Set seed for reproducibility
np.random.seed(100)

# Generate a 6x10 array of random integers from 1 to 10
arr = np.random.randint(1, 11, size=(6, 10))

# Create a result array with 6 rows and a number of columns equal to the maximum value in arr
result = np.zeros((arr.shape[0], arr.max()), dtype=int)

# Loop over the rows in arr
for i in range(arr.shape[0]):
    # Get the unique values and their counts for the current row
    unique, counts = np.unique(arr[i], return_counts=True)
    # Assign the counts to the appropriate positions in the result array
    result[i, unique-1] = counts

# Display the result array
print(result)


[[1 0 2 1 1 1 0 2 2 0]
 [2 1 3 0 1 0 1 0 1 1]
 [0 3 0 2 3 1 0 1 0 0]
 [1 0 2 1 0 1 0 2 1 2]
 [2 2 2 0 0 1 1 1 1 0]
 [1 1 1 1 1 2 0 0 2 1]]


Problem  13

Compute the one-hot encodings (dummy binary variables for each unique value in the array)

In [ ]:
array = np.array([1, 0, 2, 1, 0])  # Create a numpy array with 5 elements
#display(array)
unique_values = np.unique(array)  # Find the unique elements in the array and store them in a new array
#display(unique_values)
one_hot_encodings = np.eye(len(unique_values))[array]  # Create a one-hot encoding of the array using an identity matrix and the unique values of the array
# np.eye(len(unique_values)) creates an identity matrix with number of rows/columns equal to the length of unique values
# [array] indexes the identity matrix such that for each element in the original array, a one-hot encoding is created
display(one_hot_encodings)  # Display the one-hot encoding of the array


array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

Problem  14

Create the ranks for the given numeric array a.

Input:



```
np.random.seed(10)
a = np.random.randint(20, size=10)
print(a)
#> [ 9  4 15  0 17 16 17  8  9  0]
```

Desired output:

```
[4 2 6 0 8 7 9 3 5 1]
```

In [ ]:
np.random.seed(10) # set seed value for random number generator
a = np.random.randint(20, size=10) # generate random integer values between 0 to 20 of length 10
display("Actual array",a) # display the actual array
order = a.argsort() # sort the indices of each element of the actual array in ascending order
display('sorted index of actual array',order) # display the sorted indices of the actual array
re_order = order.argsort() # resort the indices of the actual sorted array to get the desired output
display("resorted index of actual sorted array",re_order) # display the resorted indices of the actual sorted array


'Actual array'

array([ 9,  4, 15,  0, 17, 16, 17,  8,  9,  0])

'sorted index of actual array'

array([3, 9, 1, 7, 0, 8, 2, 5, 4, 6])

'resorted index of actual sorted array'

array([4, 2, 6, 0, 8, 7, 9, 3, 5, 1])

Problem  15

Create a rank array of the same shape as a given numeric array a.

Input:



```
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)
#> [[ 9  4 15  0 17]
#>  [16 17  8  9  0]]
```


Desired output:



```
#> [[4 2 6 0 8]
#>  [7 9 3 5 1]]
```



In [ ]:
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
display("actual array ",a)

# Convert the 2D array into a 1D array
convert_1D = np.ravel(a)
display("conversion of actual 2D array into 1D array by np.ravel",convert_1D)

# Sort the index of the actual converted 1D array using np.argsort
ranked = np.argsort(convert_1D)
display("sorted the index of of actual converted 1D array by np.argsort",ranked)

# Resort the index by np.argsort
np_argsort = np.argsort(ranked)
display("again resort the index by np.argsort",np_argsort)

# Reshape np_argsort to have the same shape as the original array 'a'
desire_output = np_argsort.reshape(a.shape)
display("np_argsort.reshape(a.shape) to give the same shape as the array a had",desire_output)


'actual array '

array([[ 9,  4, 15,  0, 17],
       [16, 17,  8,  9,  0]])

'conversion of actual 2D array into 1D array by np.ravel'

array([ 9,  4, 15,  0, 17, 16, 17,  8,  9,  0])

'sorted the index of of actual converted 1D array by np.argsort'

array([3, 9, 1, 7, 0, 8, 2, 5, 4, 6])

'again resort the index by np.argsort'

array([4, 2, 6, 0, 8, 7, 9, 3, 5, 1])

'np_argsort.reshape(a.shape) to give the same shape as the array a had'

array([[4, 2, 6, 0, 8],
       [7, 9, 3, 5, 1]])

Problem  16

Compute the min-by-max for each row for given 2d numpy array

Input:

```
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a
#> array([[9, 9, 4],
#>        [8, 8, 1],
#>        [5, 3, 6],
#>        [3, 3, 3],
#>        [2, 1, 9]])
```

Desired Output:

```
array([ 0.44444444,  0.125     ,  0.5       ,  1.        ,  0.11111111])
```

In [ ]:
np.random.seed(100) # set the seed for reproducibility
a = np.random.randint(1,10, [5,3]) # create a 5x3 array with random integers between 1 and 10
display(a) # display the actual array
print('')
min = np.amin(a,axis=1) # get the minimum value from each row of the actual array using np.amin() function
display('np.amin(a,axis=1) it bring the min value from each row of actual array',min)
print('')
max = np.amax(a,axis=1) # get the maximum value from each row of the actual array using np.amax() function
display('np.amax(a,axis=1) it bring the max value from each row of actual array',max)
print('')
min_by_max = min/max # divide the minimum value by the maximum value for each row
display('Desired Output:',min_by_max) # display the desired output

array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

'np.amin(a,axis=1) it bring the min value from each row of actual array'

array([4, 1, 3, 3, 1])

'np.amax(a,axis=1) it bring the max value from each row of actual array'

array([9, 8, 6, 3, 9])

'Desired Output:'

array([0.44444444, 0.125     , 0.5       , 1.        , 0.11111111])

Problem  17

Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False

Input
```
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)
#> Array: [0 0 3 0 2 4 2 2 2 2]
```
Desired Output:
```
#> [False  True False  True False False  True  True  True  True]
```

In [ ]:
# Set random seed for reproducibility
np.random.seed(100)

# Generate a random array with integers between 0 and 4
a = np.random.randint(0, 5, 10)

# Display the generated array
print("Array: ", a)

# Find the unique elements in the array and their respective counts
unique, counts = np.unique(a, return_counts=True)

# Create a boolean array to mark the duplicates
duplicates = np.zeros(a.shape, dtype=bool)

# Mark the elements which occur more than once as duplicates
duplicates[np.in1d(a, unique[counts > 1])] = True

# Display the boolean array indicating the duplicate elements
print("Duplicates: ", duplicates)


Array:  [0 0 3 0 2 4 2 2 2 2]
Duplicates:  [ True  True False  True  True False  True  True  True  True]


Problem  18

Drop all nan values from a 1D numpy array

Input:
```
np.array([1,2,3,np.nan,5,6,7,np.nan])
```
Desired Output:
```
array([ 1.,  2.,  3.,  5.,  6.,  7.])
```

In [ ]:
# Set seed for reproducibility
np.random.seed(100)

# Create an array with some elements as NaN
a = np.array([1,2,3,np.nan,5,6,7,np.nan])

# Display the array
display(a)

# Get a boolean mask of non-NaN values in the array
mask = ~np.isnan(a)

# Display the non-NaN values using the boolean mask
display(a[mask])


array([ 1.,  2.,  3., nan,  5.,  6.,  7., nan])

array([1., 2., 3., 5., 6., 7.])

Problem 19

Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.

Input:
```
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
```
Desired Output:
```
#> array([2, 5])
```

In [ ]:
# The code defines a function called "find_peaks" which takes an array a as input
def find_peaks(a):
  # Creates an empty list called "peaks" to store the peak indices
  peaks = []
  
  # Loops through the array indices from the second element to the second last element
  for i in range(1, len(a) - 1):
    # If the current element is greater than its two neighbors, it is a peak
    if a[i] > a[i - 1] and a[i] > a[i + 1]:
      # Adds the current index to the "peaks" list
      peaks.append(i)
  
  # Returns the "peaks" list
  return peaks

# Defines an array "a" with some values
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

# Calls the "find_peaks" function with the array "a" as input and stores the returned list of peak indices in a variable called "peaks"
peaks = find_peaks(a)

# Prints the list of peak indices
print(peaks)


[2, 5]


Problem 20

Subtract the 1d array b_1d from the 2d array a_2d, such that each item of b_1d subtracts from respective row of a_2d.


Input
```
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,1,1]

```
Desired Output:
```
#> [[2 2 2]
#>  [2 2 2]
#>  [2 2 2]]
```

In [ ]:
# Create a 2D numpy array with shape (3, 3) filled with the value 3
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])

# Create a 1D numpy array with length 3 filled with the value 1
b_1d = np.array([1,1,1])

# Loop through each row in the 2D array
for a in a_2d:
  
  # Subtract the 1D array from the current row in the 2D array, element-wise
  result = a - b_1d
  
  # Increment each value in the 1D array by 1
  b_1d += 1
  
  # Display the resulting array after subtraction
  display(result)


array([2, 2, 2])

array([2, 2, 2])

array([2, 2, 2])

Problem 21

Find the index of 5th repetition of number 1 in x.

Input:

```
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
```



In [ ]:
# Define an array
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

# Find the indices where the value equals 1
indices = np.where(x == 1)[0]

# Get the index of the fifth occurrence of 1
fifth_rep = indices[4]

# Print the index
print(fifth_rep) # this will output the index of the fifth occurrence of 1 in the array


8


Problem 22

Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers

In [ ]:
# create a one-dimensional numpy array 'a' using arange() function with starting value 5, ending value 33 (exclusive) and step 3
a = np.arange(5, 33, 3)

# display the numpy array 'a'
display(a)

# # display the length of the numpy array 'a'
# This line is commented out using the '#' symbol, which means it will be ignored by the interpreter and not executed.
# If you remove the '#' symbol, the line will display the length of the numpy array 'a'. 
# However, it is not necessary to display the length of the array in this case since we can easily determine it from the values passed to arange(). 
# If you do want to display the length of the array, you can uncomment this line by removing the '#' symbol.


array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

Problem 23

 From the given 1d array arr, generate a 2d matrix using strides, with a window length of 4 and strides of 2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]

Input:
```
arr = np.arange(15) 
arr
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
```

Desired Output:
```
#> [[ 0  1  2  3]
#>  [ 2  3  4  5]
#>  [ 4  5  6  7]
#>  [ 6  7  8  9]
#>  [ 8  9 10 11]
#>  [10 11 12 13]]
```

In [ ]:
# define a function named 'rolling' that takes two arguments, an array 'a' and a window size 'window'
def rolling(a, window):
    
    # calculate the shape of the output array
    shape = (a.size - window + 1, window)
    
    # calculate the strides of the output array
    strides = (a.itemsize, a.itemsize)
    
    # return a new numpy array with the specified shape and strides
    # the 'as_strided' function returns a view of the input array 'a' with the given shape and strides
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)

# create a one-dimensional numpy array 'a' with 15 elements using arange() function
a = np.arange(15)

# call the 'rolling' function with the array 'a' and a window size of 4, and print the result
print(rolling(a, 4))


[[ 0  1  2  3]
 [ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
