<a href="https://colab.research.google.com/github/atif4/Q2/blob/gh-pages/numpy_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem  1

Convert a 1D array to a 2D array with 2 rows

Input:
```
np.arange(10)

#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

Output:


```
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])
```



In [1]:
import numpy as np
a = np.arange(2*5)
display(a)
display(a.reshape(2,5))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Problem  2

Extract all odd numbers from arr

```
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```



In [2]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_odd = arr[arr%2!=0]
display("ODD",arr_odd)
arr_even = arr[arr%2==0]
display("EVEN",arr_even)

'ODD'

array([1, 3, 5, 7, 9])

'EVEN'

array([0, 2, 4, 6, 8])

Problem  3

Replace all odd numbers in arr with -1

```
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

Output:


```
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
```



In [3]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2!=0] = -1
display(arr)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Problem  4

Replace all odd numbers in arr with -1 without changing arr

Input:

`arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])`

Desired Output:

```
out
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr
#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```




In [4]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
copy = np.copy(arr)
arr[arr%2!=0] = -1
display("output",arr)
display("arr",copy)

'output'

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

'arr'

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Problem  5

Stack arrays a and b vertically

Input



```
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```


Desired Output:


```
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
```




In [5]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
#display("a",a)
#display("b",b)
display("Desired Output: vstack",np.vstack((a,b)))

'Desired Output: vstack'

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Problem  6

Stack the arrays a and b horizontally.

Input


```
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```


Desired Output:



```
array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
```




In [6]:
display("Desired Output: np.hstack",np.hstack((a,b)))

'Desired Output: np.hstack'

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

Problem  7

Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:



```
a = np.array([1,2,3])
```


Desired Output:



```
#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```




In [7]:
a = np.array([1,2,3])
#display("a",a)

repeat = np.repeat(a, 3)
#display("np.repeat:",repeat)

"""Numpy tile (np.tile) in Python simply repeats the numbers of elements present in an array. Suppose you have a numpy array [4,5,6,7],
then np.tile([4,5,6,7], 3) will duplicate the elements three times and make a new array."""
tile = np.tile([1, 2, 3], 3)
#display("np.tile",tile)

"""np.r_[] concatenates arrays along first axis."""
r_ = np.r_[repeat, tile]
display("Desired Output: np.r_",r_)

"""np.c_[] concatenates arrays along second axis"""
c_ = np.c_[repeat, tile]
#display("np.c_",c_)

'Desired Output: np.r_'

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Problem  8

From array a remove all items present in array b

Input:


```
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
```

Desired Output:

```
array([1,2,3,4])
```




In [8]:

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
"""Find the set difference of two arrays.
Return the unique values in ar1 that are not in ar2."""
diff_of_a_b = np.setdiff1d(a, b)
display("Desired Output: np.setdiff1d",diff_of_a_b)

'Desired Output: np.setdiff1d'

array([1, 2, 3, 4])

Problem  9

Get the positions where elements of a and b match

Input:



```
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```


Desired Output:



```
(array([1, 3, 5, 7]),)
```



In [9]:
a = np.array([1,2,3 ,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
display("Desired Output:",np.where(a==b))

'Desired Output:'

(array([1, 3, 5, 7]),)

Problem  10

Swap columns 1 and 2 in the array arr.

```
arr = np.arange(9).reshape(3,3)
```

Output:



```
array([[1, 0, 2],
      [4, 3, 5],
      [7, 6, 8]])
```




In [10]:
arr = np.arange(9).reshape(3,3)
#display("arr:",arr)
swap = arr[:,[1,0,2]]
display("output swap:",swap)

'output swap:'

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

Problem  11

From the array a, replace all values greater than 30 to 30 and less than 10 to 10.

Input:


```
np.random.seed(100)
a = np.random.uniform(1,50, 20)
```


In [11]:
np.random.seed(100) #randomly genrated will be same once they genrated by seed() 
a = np.random.uniform(1,50, 20)
#display("a",a)
a[a >= 30] = 30
a[a <= 10] = 10
display("a",a)
#np.where(a>=30,30,a)

'a'

array([27.62684215, 14.64009987, 21.80136195, 30.        , 10.        ,
       10.        , 30.        , 30.        , 10.        , 29.17957314,
       30.        , 11.25090398, 10.08108276, 10.        , 11.76517714,
       30.        , 30.        , 10.        , 30.        , 14.42961361])

Problem  12

Compute the counts of unique values row-wise.

Input:



```
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr
> array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
>        [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
>        [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
>        [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
>        [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
>        [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])
```



Desired Output:



```
> [[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
>  [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
>  [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
>  [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
>  [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
>  [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]
```



In [12]:
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
result = np.zeros((arr.shape[0], arr.max()), dtype=int)
for i in range(arr.shape[0]):
    unique, counts = np.unique(arr[i], return_counts=True)
    result[i, unique-1] = counts
display(result)

array([[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
       [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
       [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
       [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
       [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]])

Problem  13

Compute the one-hot encodings (dummy binary variables for each unique value in the array)

In [13]:
array = np.array([1, 0, 2, 1, 0])
#display(array)
unique_values = np.unique(array)
#display(unique_values)
one_hot_encodings = np.eye(len(unique_values))[array] # np.eye(len(unique_values)) make the identity Matrix and [array] help to make each for onehotencode 
display(one_hot_encodings)

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

Problem  14

Create the ranks for the given numeric array a.

Input:



```
np.random.seed(10)
a = np.random.randint(20, size=10)
print(a)
#> [ 9  4 15  0 17 16 17  8  9  0]
```

Desired output:

```
[4 2 6 0 8 7 9 3 5 1]
```

In [14]:
np.random.seed(10)
a = np.random.randint(20, size=10)
display("Actual array",a)
order = a.argsort() # it sort the index of each element of the actual array 
display('sorted index of actual array',order)
re_order = order.argsort() # it resort the index of actual sorted array to get desire output
display("resorted index of actual sorted array",re_order)

'Actual array'

array([ 9,  4, 15,  0, 17, 16, 17,  8,  9,  0])

'sorted index of actual array'

array([3, 9, 1, 7, 0, 8, 2, 5, 4, 6])

'resorted index of actual sorted array'

array([4, 2, 6, 0, 8, 7, 9, 3, 5, 1])

Problem  15

Create a rank array of the same shape as a given numeric array a.

Input:



```
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)
#> [[ 9  4 15  0 17]
#>  [16 17  8  9  0]]
```


Desired output:



```
#> [[4 2 6 0 8]
#>  [7 9 3 5 1]]
```



In [15]:
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
display("actual array ",a)
print("")
convert_1D = np.ravel(a)
display("conversion of actual 2D array into 1D array by np.ravel",convert_1D) # 1st it convert 2d array into 1d
print("")
ranked = np.argsort(convert_1D) # sorted the index of of actual converted 1D array by np.argsort
display("sorted the index of of actual converted 1D array by np.argsort",ranked)
print('')
np_argsort = np.argsort(ranked)
display("again resort the index by np.argsort",np_argsort)
print('')
desire_output = np_argsort.reshape(a.shape) # np_argsort.reshape(a.shape) to give the same shape as the array a had  
display("np_argsort.reshape(a.shape) to give the same shape as the array a had",desire_output)

'actual array '

array([[ 9,  4, 15,  0, 17],
       [16, 17,  8,  9,  0]])

'conversion of actual 2D array into 1D array by np.ravel'

array([ 9,  4, 15,  0, 17, 16, 17,  8,  9,  0])

'sorted the index of of actual converted 1D array by np.argsort'

array([3, 9, 1, 7, 0, 8, 2, 5, 4, 6])

'again resort the index by np.argsort'

array([4, 2, 6, 0, 8, 7, 9, 3, 5, 1])

'np_argsort.reshape(a.shape) to give the same shape as the array a had'

array([[4, 2, 6, 0, 8],
       [7, 9, 3, 5, 1]])

Problem  16

Compute the min-by-max for each row for given 2d numpy array

Input:

```
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a
#> array([[9, 9, 4],
#>        [8, 8, 1],
#>        [5, 3, 6],
#>        [3, 3, 3],
#>        [2, 1, 9]])
```

Desired Output:

```
array([ 0.44444444,  0.125     ,  0.5       ,  1.        ,  0.11111111])
```

In [16]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
display(a)
print('')
min = np.amin(a,axis=1)# it bring the min value from each row of actual array 
display('np.amin(a,axis=1) it bring the min value from each row of actual array',min)
print('')
max = np.amax(a,axis=1)
display('np.amax(a,axis=1) it bring the max value from each row of actual array',max)
print('')
min_by_max = min/max
display('Desired Output:',min_by_max)

array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

'np.amin(a,axis=1) it bring the min value from each row of actual array'

array([4, 1, 3, 3, 1])

'np.amax(a,axis=1) it bring the max value from each row of actual array'

array([9, 8, 6, 3, 9])

'Desired Output:'

array([0.44444444, 0.125     , 0.5       , 1.        , 0.11111111])

Problem  17

Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False

Input
```
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)
#> Array: [0 0 3 0 2 4 2 2 2 2]
```
Desired Output:
```
#> [False  True False  True False False  True  True  True  True]
```

In [17]:
import numpy as np

np.random.seed(100)
a = np.random.randint(0, 5, 10)
display('Array: ', a)

unique, counts = np.unique(a, return_counts=True)
duplicates = np.zeros(a.shape, dtype=bool)
duplicates[np.in1d(a, unique[counts > 1])] = True
display('Duplicates: ', duplicates)


'Array: '

array([0, 0, 3, 0, 2, 4, 2, 2, 2, 2])

'Duplicates: '

array([ True,  True, False,  True,  True, False,  True,  True,  True,
        True])

Problem  18

Drop all nan values from a 1D numpy array

Input:
```
np.array([1,2,3,np.nan,5,6,7,np.nan])
```
Desired Output:
```
array([ 1.,  2.,  3.,  5.,  6.,  7.])
```

In [18]:
from numpy.lib.function_base import delete
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
display(a)
a[~np.isnan(a)]

array([ 1.,  2.,  3., nan,  5.,  6.,  7., nan])

array([1., 2., 3., 5., 6., 7.])

Problem 19

Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.

Input:
```
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
```
Desired Output:
```
#> array([2, 5])
```

In [25]:
"""This code first defines a function find_peaks which takes in an array a and returns the indices of the peaks in the array.
 The function uses a for loop to iterate through the elements of the array and checks if the current element is greater than its two neighbors.
  If it is, the index is added to the peaks list. Finally, the function returns the peaks list."""
def find_peaks(a):
  peaks = []
  for i in range(1, len(a) - 1):
    if a[i] > a[i - 1] and a[i] > a[i + 1]:
      peaks.append(i)
  return peaks
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
peaks = find_peaks(a)
print(peaks)

[2, 5]


Problem 20

Subtract the 1d array b_1d from the 2d array a_2d, such that each item of b_1d subtracts from respective row of a_2d.


Input
```
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,1,1]

```
Desired Output:
```
#> [[2 2 2]
#>  [2 2 2]
#>  [2 2 2]]
```

In [73]:
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,1,1])
for a in a_2d:
  result = a-b_1d
  b_1d+=1
  display(result)

array([2, 2, 2])

array([2, 2, 2])

array([2, 2, 2])

Problem 21

Find the index of 5th repetition of number 1 in x.

Input:

```
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
```



In [75]:
import numpy as np
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
indices = np.where(x == 1)[0]
#display(indices)
fifth_rep = indices[4]
print(fifth_rep)


8


Problem 22

Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers

In [67]:
a = np.arange(5, 33, 3)
display(a)
#display(len(a))

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

Problem 23

 From the given 1d array arr, generate a 2d matrix using strides, with a window length of 4 and strides of 2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]

Input:
```
arr = np.arange(15) 
arr
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
```

Desired Output:
```
#> [[ 0  1  2  3]
#>  [ 2  3  4  5]
#>  [ 4  5  6  7]
#>  [ 6  7  8  9]
#>  [ 8  9 10 11]
#>  [10 11 12 13]]
```

In [68]:
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)

a = np.arange(15) 
print(rolling(a, 4))

[[ 0  1  2  3]
 [ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
