In [13]:
import pandas as pd 
# to handle stureture data or tabular data
# new excle is pandas 
# pyscrepe 
# 2 type of core datatype 1)series 2)DataFrame 
# basic of pandas is Series 
# series and dataframe has their own attributes
# pandas support hateroenouse data but numpy support homogenius data
# two things automatically display datatype and index 
# multiindex also done in pandas but in Numpy it does nt 
# any alterive datatype can be convert into series and you can be control their index as well 

import numpy  as np

In [14]:
s1 =  pd.Series([1,2,3,4])
# s1 is instead 
# Series is class 
# datatype is [1,2,3,4]

In [15]:
s1

0    1
1    2
2    3
3    4
dtype: int64

In [16]:
s1.values

array([1, 2, 3, 4], dtype=int64)

In [17]:
s1.index

RangeIndex(start=0, stop=4, step=1)

In [18]:
s1.index=[list("abcd")]

In [19]:
s1.index

MultiIndex([('a',),
            ('b',),
            ('c',),
            ('d',)],
           )

In [20]:
s1

a    1
b    2
c    3
d    4
dtype: int64

In [21]:
s1.index.dtype

dtype('O')

In [54]:
s1.index

MultiIndex([('a',),
            ('b',),
            ('c',),
            ('d',)],
           )

In [22]:
s2 = pd.Series([44, 33, 55, 77],index=(list("afgh")))
s3 = pd.Series([44, 33, 55, 77],index=(list("aegb")))

In [23]:
s2

a    44
f    33
g    55
h    77
dtype: int64

In [24]:
s3

a    44
e    33
g    55
b    77
dtype: int64

In [25]:
s2+s3

a     88.0
b      NaN
e      NaN
f      NaN
g    110.0
h      NaN
dtype: float64

In [26]:
s1+s2

F:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\multi.py:3635: RuntimeWarning: The values in the array are unorderable. Pass `sort=False` to suppress this warning.
  result = lib.fast_unique_multiple([self._values, rvals], sort=sort)


a   NaN
b   NaN
c   NaN
d   NaN
a   NaN
f   NaN
g   NaN
h   NaN
dtype: float64

In [27]:
s1

a    1
b    2
c    3
d    4
dtype: int64

In [28]:
s2

a    44
f    33
g    55
h    77
dtype: int64

In [29]:
s1+s2

F:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\multi.py:3635: RuntimeWarning: The values in the array are unorderable. Pass `sort=False` to suppress this warning.
  result = lib.fast_unique_multiple([self._values, rvals], sort=sort)


a   NaN
b   NaN
c   NaN
d   NaN
a   NaN
f   NaN
g   NaN
h   NaN
dtype: float64

In [30]:
s4=pd.Series(range(1,10))

In [31]:
s4

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [32]:
s5=pd.Series(range(3,13))

In [33]:
s5

0     3
1     4
2     5
3     6
4     7
5     8
6     9
7    10
8    11
9    12
dtype: int64

In [34]:
s4+s5

0     4.0
1     6.0
2     8.0
3    10.0
4    12.0
5    14.0
6    16.0
7    18.0
8    20.0
9     NaN
dtype: float64

In [35]:
s4[2:5]=110

In [36]:
s4

0      1
1      2
2    110
3    110
4    110
5      6
6      7
7      8
8      9
dtype: int64

# Lambda Functions : Anonymous Functions (IIF)

In [62]:
new = pd.Series([99, 100, 89, 50 ,45,30], index=['Ahmed', 'Ali', 'Faisal', 'Hassan', 'Aqsa', 'Waji'])

In [63]:
def get_makr(mark):
    return mark/100

In [64]:
new

Ahmed      99
Ali       100
Faisal     89
Hassan     50
Aqsa       45
Waji       30
dtype: int64

In [66]:
new =  new.apply(get_makr)

In [67]:
new.apply(lambda x: x*100)

Ahmed     0.99
Ali       1.00
Faisal    0.89
Hassan    0.50
Aqsa      0.45
Waji      0.30
dtype: float64

In [68]:
new = new.apply(lambda x: np.where(x>40, "Pass", "Fail"))
new
#most simple function use for small work

Ahmed     Fail
Ali       Fail
Faisal    Fail
Hassan    Fail
Aqsa      Fail
Waji      Fail
dtype: object

In [70]:
#linspace
np.linspace(0,10,10)# generate romdon data which evenly distributed

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [71]:
new.count()

6

In [72]:
new.value_counts()

Fail    6
dtype: int64

In [73]:
new[['Ahmed','Ali' ]]

Ahmed    Fail
Ali      Fail
dtype: object

In [74]:
s7 = pd.Series([1,2,3,np.nan, np.nan])
s7

0    1.0
1    2.0
2    3.0
3    NaN
4    NaN
dtype: float64

In [79]:
np.random.seed(1)
s1 = pd.Series(np.random.randn(3))
s2 = pd.Series(np.random.randn(3))
print(f"s1\n{s1}\n\ns2\n{s2}")

s1
0    1.624345
1   -0.611756
2   -0.528172
dtype: float64

s2
0   -1.072969
1    0.865408
2   -2.301539
dtype: float64


In [80]:
combined = pd.concat([s1, s2])
combined

0    1.624345
1   -0.611756
2   -0.528172
0   -1.072969
1    0.865408
2   -2.301539
dtype: float64

In [81]:
combined.reset_index(drop=True,inplace=True)

In [51]:
lambda x : True if (x > 10 and x < 20) else False

<function __main__.<lambda>(x)>

In [82]:
combined

0    1.624345
1   -0.611756
2   -0.528172
3   -1.072969
4    0.865408
5   -2.301539
dtype: float64

In [83]:
combined[4] = 2345
combined

0       1.624345
1      -0.611756
2      -0.528172
3      -1.072969
4    2345.000000
5      -2.301539
dtype: float64

In [84]:
del combined[4]

In [88]:
combined[1:5] =100
combined

0      1.624345
1    100.000000
2    100.000000
3    100.000000
5    100.000000
dtype: float64

In [85]:
combined

0    1.624345
1   -0.611756
2   -0.528172
3   -1.072969
5   -2.301539
dtype: float64

In [93]:
def gen_age(age):
    if age<=20:
        return 'ten ager'
    elif age<40:
        return 'Young '
    elif age<60:
        return 'experience'
    else:
        return 'sero'

# Pandas Data Frame

In [95]:
students = {'rolls':[1,2,3,4,5,6],
            'names':['Ali','Amjad', 'Saima', 'Qaiser','Hamid','Nasir'], 
            'courses':['Python', 'Pandas', 'Numpy','Pandas', 'Numpy', "Python"], 
            'mode':['Online', 'Onsite','Online', 'Onsite','Online', 'Onsite']}


In [96]:
# Creating a data frame
df  = pd.DataFrame(students)
df

rolls   names courses    mode
0      1     Ali  Python  Online
1      2   Amjad  Pandas  Onsite
2      3   Saima   Numpy  Online
3      4  Qaiser  Pandas  Onsite
4      5   Hamid   Numpy  Online
5      6   Nasir  Python  Onsite

In [97]:
type(df[['rolls', 'names']])

pandas.core.frame.DataFrame

In [98]:
type(df['rolls'])

pandas.core.series.Series

In [99]:
type(df[['rolls']])

pandas.core.frame.DataFrame

In [100]:
np.array([[9]]).ndim

2

In [101]:
lst=[[55,66,77],[2,4,5],[4,5,6]]

In [102]:
lst

[[55, 66, 77], [2, 4, 5], [4, 5, 6]]

In [103]:
pd.DataFrame(lst,index=[1,2,3],columns=["a","b","c"] )

a   b   c
1  55  66  77
2   2   4   5
3   4   5   6

In [104]:
#Accessing data
# Columns
df['courses']

0    Python
1    Pandas
2     Numpy
3    Pandas
4     Numpy
5    Python
Name: courses, dtype: object

In [105]:
df[['courses', 'names']]

courses   names
0  Python     Ali
1  Pandas   Amjad
2   Numpy   Saima
3  Pandas  Qaiser
4   Numpy   Hamid
5  Python   Nasir

In [106]:
df['Country'] = "Pakistan"
df

rolls   names courses    mode   Country
0      1     Ali  Python  Online  Pakistan
1      2   Amjad  Pandas  Onsite  Pakistan
2      3   Saima   Numpy  Online  Pakistan
3      4  Qaiser  Pandas  Onsite  Pakistan
4      5   Hamid   Numpy  Online  Pakistan
5      6   Nasir  Python  Onsite  Pakistan

In [107]:
df['Ages'] = [23,34,23,21,20,19]
df

rolls   names courses    mode   Country  Ages
0      1     Ali  Python  Online  Pakistan    23
1      2   Amjad  Pandas  Onsite  Pakistan    34
2      3   Saima   Numpy  Online  Pakistan    23
3      4  Qaiser  Pandas  Onsite  Pakistan    21
4      5   Hamid   Numpy  Online  Pakistan    20
5      6   Nasir  Python  Onsite  Pakistan    19

In [108]:
dic = {'Ali':34, 'Amjad':45, "Saima":23, "Hamid":34, "Nasir":20,'Qaiser':45}

In [109]:
df['newAges'] = df.names.map(dic)

In [110]:
df['Status'] = ["Pass" if age>25 else "Fails" for age in df['Ages']]

In [111]:
df

rolls   names courses    mode   Country  Ages  newAges Status
0      1     Ali  Python  Online  Pakistan    23       34  Fails
1      2   Amjad  Pandas  Onsite  Pakistan    34       45   Pass
2      3   Saima   Numpy  Online  Pakistan    23       23  Fails
3      4  Qaiser  Pandas  Onsite  Pakistan    21       45  Fails
4      5   Hamid   Numpy  Online  Pakistan    20       34  Fails
5      6   Nasir  Python  Onsite  Pakistan    19       20  Fails

In [112]:
df['City'] = df['mode'].apply(lambda x: 'Karachi' if x=="Onsite" else "Outside Khi")

In [113]:
def generationAssign(age):
    if age <20:
        return "Teen Ager"
    elif age<40:
        return "Young"
    elif age <60:
        return "Matured"
    else:
        return 'Senior'

In [114]:
df['Generation Next'] = df.Ages.apply(generationAssign)

In [115]:
df

rolls   names courses    mode   Country  Ages  newAges Status         City  \
0      1     Ali  Python  Online  Pakistan    23       34  Fails  Outside Khi   
1      2   Amjad  Pandas  Onsite  Pakistan    34       45   Pass      Karachi   
2      3   Saima   Numpy  Online  Pakistan    23       23  Fails  Outside Khi   
3      4  Qaiser  Pandas  Onsite  Pakistan    21       45  Fails      Karachi   
4      5   Hamid   Numpy  Online  Pakistan    20       34  Fails  Outside Khi   
5      6   Nasir  Python  Onsite  Pakistan    19       20  Fails      Karachi   

  Generation Next  
0           Young  
1           Young  
2           Young  
3           Young  
4           Young  
5       Teen Ager

In [116]:
df.to_excel("student.xlsx")

In [117]:
a =np.array([1,2,3])

In [118]:
a

array([1, 2, 3])

In [121]:
a = a*10
a

array([100, 200, 300])

In [122]:
df['Generation Next']

0        Young
1        Young
2        Young
3        Young
4        Young
5    Teen Ager
Name: Generation Next, dtype: object

In [124]:
data = pd.read_csv("astronauts.csv")
data

Name    Year  Group   Status Birth Date  \
0          Joseph M. Acaba  2004.0   19.0   Active  5/17/1967   
1           Loren W. Acton     NaN    NaN  Retired   3/7/1936   
2         James C. Adamson  1984.0   10.0  Retired   3/3/1946   
3          Thomas D. Akers  1987.0   12.0  Retired  5/20/1951   
4              Buzz Aldrin  1963.0    3.0  Retired  1/20/1930   
..                     ...     ...    ...      ...        ...   
352          David A. Wolf  1990.0   13.0  Retired  8/23/1956   
353  Neil W. Woodward III   1998.0   17.0  Retired  7/26/1962   
354       Alfred M. Worden  1966.0    5.0  Retired   2/7/1932   
355          John W. Young  1962.0    2.0  Retired  9/24/1930   
356        George D. Zamka  1998.0   17.0  Retired  6/29/1962   

           Birth Place Gender  \
0        Inglewood, CA   Male   
1         Lewiston, MT   Male   
2           Warsaw, NY   Male   
3        St. Louis, MO   Male   
4        Montclair, NJ   Male   
..                 ...    ...   
352   Indianapolis, IN   Male   
353        Chicago, IL   Male   
354        Jackson, MI   Male   
355  San Francisco, CA   Male   
356    Jersey City, NJ   Male   

                                            Alma Mater  \
0    University of California-Santa Barbara; Univer...   
1     Montana State University; University of Colorado   
2            US Military Academy; Princeton University   
3                         University of Missouri-Rolla   
4                             US Military Academy; MIT   
..                                                 ...   
352              Purdue University; Indiana University   
353  MIT; University of Texas-Austin; George Washin...   
354        US Military Academy; University of Michigan   
355                    Georgia Institute of Technology   
356  US Naval Academy; Florida Institute of Technology   

          Undergraduate Major                            Graduate Major  \
0                     Geology                                   Geology   
1         Engineering Physics                             Solar Physics   
2                 Engineering                     Aerospace Engineering   
3         Applied Mathematics                       Applied Mathematics   
4      Mechanical Engineering                              Astronautics   
..                        ...                                       ...   
352    Electrical Engineering                                  Medicine   
353                   Physics              Physics; Business Management   
354          Military Science  Aeronautical & Astronautical Engineering   
355  Aeronautical Engineering                                       NaN   
356               Mathematics                    Engineering Management   

    Military Rank            Military Branch  Space Flights  \
0             NaN                        NaN              2   
1             NaN                        NaN              1   
2         Colonel          US Army (Retired)              2   
3         Colonel     US Air Force (Retired)              4   
4         Colonel     US Air Force (Retired)              2   
..            ...                        ...            ...   
352           NaN                        NaN              3   
353     Commander                    US Navy              0   
354       Colonel     US Air Force (Retired)              1   
355       Captain          US Navy (Retired)              6   
356       Colonel  US Marine Corps (Retired)              2   

     Space Flight (hr)  Space Walks  Space Walks (hr)  \
0                 3307            2              13.0   
1                  190            0               0.0   
2                  334            0               0.0   
3                  814            4              29.0   
4                  289            2               8.0   
..                 ...          ...               ...   
352               4044            7              41.0   
353                  0           