# Numpy
- numpy is array 
- it is fast 
- 1d = vector 
- 2d = Matrix 
- 3d = cube
- Numerical Python
- Fastest
- Vectorised Operation
- Contigous Memory

In [2]:
import numpy as np

In [8]:
x = np.arange(10)
(f"x: {x} size: {x.size} shape: {x.shape} dimension {x.ndim}")

'x: [0 1 2 3 4 5 6 7 8 9] size: 10 shape: (10,) dimension 1'

'x: [0 1 2 3 4 5 6 7 8 9] size: 10 shape: (10,) dimension 1'

In [4]:
range(10)

range(0, 10)

In [5]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [21]:
arr2d = np.arange(20).reshape(4,5)

In [22]:
arr2d
print(f"array:\n {arr2d}\n size: {arr2d.size} shape: {arr2d.shape} dimension {arr2d.ndim}")

array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
 size: 20 shape: (4, 5) dimension 2


In [23]:
arr2d.flatten() # 1000 can be convert into 1 dimension 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [24]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [25]:
arr2d.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [42]:
print(f"arr2d:\n {arr2d}\narr2d[3,2]: {arr2d[3,2]} \narr2d[3][2]: {arr2d[3][2]}")

arr2d:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
arr2d[3,2]: 17 
arr2d[3][2]: 17


In [51]:
arr2d /10

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4],
       [1.5, 1.6, 1.7, 1.8, 1.9]])

In [27]:
arr=np.array([10])
print(f"array: {arr} dimension:{arr.ndim}")

array: [10] dimension:1


In [28]:
arr=np.array(10)
print(f"array: {arr} dimension:{arr.ndim}")

array: 10 dimension:0


In [21]:
arr=np.array([[10]])
print(f"{arr} {arr.ndim}")

[[10]] 2


In [30]:
arr=np.array([[[10]]])
print(f"array: {arr} dimension:{arr.ndim}")

array: [[[10]]] dimension:3


In [31]:
arr=np.array([[[[10]]]])
print(f"array: {arr} dimension:{arr.ndim}")

array: [[[[10]]]] dimension:4


In [32]:
arr3d = np.arange(64).reshape(4,4,4)
#depth, row , column 
print(f"array: {arr} dimension:{arr.ndim}")

array: [[[[10]]]] dimension:4


In [44]:
arr3d = np.arange(81).reshape(9,3,3)
#depth, row , column 

In [48]:
print(f"arr3d: {arr3d}\n\narr3d[2]:\n {arr3d[2]}\n\narr3d[2,1,2]: {arr3d[2,1,2]}")

arr3d: [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]]

 [[45 46 47]
  [48 49 50]
  [51 52 53]]

 [[54 55 56]
  [57 58 59]
  [60 61 62]]

 [[63 64 65]
  [66 67 68]
  [69 70 71]]

 [[72 73 74]
  [75 76 77]
  [78 79 80]]]

arr3d[2]:
 [[18 19 20]
 [21 22 23]
 [24 25 26]]

arr3d[2,1,2]: 23


In [52]:
arr3d*10

array([[[  0,  10,  20],
        [ 30,  40,  50],
        [ 60,  70,  80]],

       [[ 90, 100, 110],
        [120, 130, 140],
        [150, 160, 170]],

       [[180, 190, 200],
        [210, 220, 230],
        [240, 250, 260]],

       [[270, 280, 290],
        [300, 310, 320],
        [330, 340, 350]],

       [[360, 370, 380],
        [390, 400, 410],
        [420, 430, 440]],

       [[450, 460, 470],
        [480, 490, 500],
        [510, 520, 530]],

       [[540, 550, 560],
        [570, 580, 590],
        [600, 610, 620]],

       [[630, 640, 650],
        [660, 670, 680],
        [690, 700, 710]],

       [[720, 730, 740],
        [750, 760, 770],
        [780, 790, 800]]])

In [49]:
x = np.arange(10)
x = x**2 # perment change 
print(f"x: {x}")

x: [ 0  1  4  9 16 25 36 49 64 81]


In [53]:
[n**2 for n in x]

[0, 1, 16, 81, 256, 625, 1296, 2401, 4096, 6561]

In [54]:
# mirroring = element vise operation 
a = np.arange(25).reshape(5,5)
b = np.arange(25,50).reshape(5,5)

In [55]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [56]:
b

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [57]:
a+b

array([[25, 27, 29, 31, 33],
       [35, 37, 39, 41, 43],
       [45, 47, 49, 51, 53],
       [55, 57, 59, 61, 63],
       [65, 67, 69, 71, 73]])

In [58]:
a*b

array([[   0,   26,   54,   84,  116],
       [ 150,  186,  224,  264,  306],
       [ 350,  396,  444,  494,  546],
       [ 600,  656,  714,  774,  836],
       [ 900,  966, 1034, 1104, 1176]])

In [59]:
a@b #this for multiplication 
## a.dot(b)

array([[ 400,  410,  420,  430,  440],
       [1275, 1310, 1345, 1380, 1415],
       [2150, 2210, 2270, 2330, 2390],
       [3025, 3110, 3195, 3280, 3365],
       [3900, 4010, 4120, 4230, 4340]])