### Universal Functions: Fast Element-Wise Array Functions

In [35]:
import numpy as np

In [53]:
import warnings
warnings.filterwarnings("ignore")

In [36]:
arr = np.arange(10)

In [37]:
display(arr)
sqrt = np.sqrt(arr) #sqrt Compute the square root of each element (equivalent to arr ** 0.5)
display(sqrt)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [38]:
display(arr)
sq_root = arr**0.5
display("sq_root",sq_root)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

'sq_root'

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [42]:
# square Compute the square of each element (equivalent to arr ** 2)
display(arr)
sq = arr**2
display("arr**2",sq)
np_square = np.square(arr)
display("np.square",np_square)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

'arr**2'

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

'np.square'

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [44]:
display(arr)
#exp Compute the exponent ex of each element
exp = np.exp(arr)
display("exp",exp)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

'exp'

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [54]:
"""log, log10, 
log2, log1p
Natural logarithm (base e), log base 10, log base 2, and log(1 + x), respectively
The natural logarithm log is the inverse of the exponential function, so that log(exp(x)) = x. 
The natural logarithm is logarithm in base e."""
display(arr)
log = np.log(arr)
display("log",log)
log10 = np.log10(arr)
display("log10",log10)
log1p = np.log1p(arr)
display("log1p",log1p)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

'log'

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

'log10'

array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251])

'log1p'

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [57]:
# sign Compute the sign of each element: 1 (positive), 0 (zero), or –1 (negative)
x = np.random.randn(8)
display(x)
np.sign(x)

array([ 0.29211292, -0.43243851,  1.68077287, -0.12891062,  0.16908463,
       -0.24321828,  0.05365252, -1.25405022])

array([ 1., -1.,  1., -1.,  1., -1.,  1., -1.])

In [61]:
# ceil Compute the ceiling of each element (i.e., the smallest integer greater than or equal to that number)
display(x)
np.ceil(x)

array([ 0.29211292, -0.43243851,  1.68077287, -0.12891062,  0.16908463,
       -0.24321828,  0.05365252, -1.25405022])

array([ 1., -0.,  2., -0.,  1., -0.,  1., -1.])

In [67]:
# floor Compute the floor of each element (i.e., the largest integer less than or equal to each element)
display(x)
display("np.floor",np.floor(x))

array([ 0.29211292, -0.43243851,  1.68077287, -0.12891062,  0.16908463,
       -0.24321828,  0.05365252, -1.25405022])

'np.floor'

array([ 0., -1.,  1., -1.,  0., -1.,  0., -2.])

In [69]:
# rint Round elements to the nearest integer, preserving the dtype
display(x)
display("np.rint",np.rint(x))

array([ 0.29211292, -0.43243851,  1.68077287, -0.12891062,  0.16908463,
       -0.24321828,  0.05365252, -1.25405022])

'np.rint'

array([ 0., -0.,  2., -0.,  0., -0.,  0., -1.])

In [73]:
# modf Return fractional and integral parts of array as a separate array
display(x)
display("np.modf",np.modf(x))

array([ 0.29211292, -0.43243851,  1.68077287, -0.12891062,  0.16908463,
       -0.24321828,  0.05365252, -1.25405022])

'np.modf'

(array([ 0.29211292, -0.43243851,  0.68077287, -0.12891062,  0.16908463,
        -0.24321828,  0.05365252, -0.25405022]),
 array([ 0., -0.,  1., -0.,  0., -0.,  0., -1.]))

In [14]:
"""While not common, a ufunc can return multiple arrays. modf is one example, a vec‐
torized version of the built-in Python divmod; it returns the fractional and integral
parts of a floating-point array:
modf Return fractional and integral parts of array as a separate array
"""
arr = np.random.randn(7) * 5
display("arr",arr)
remainder, whole_part = np.modf(arr)
display("remainder",remainder)
display("whole_part",whole_part)

'arr'

array([-3.67283537, -0.2458653 , -0.13894765, -4.54084001, -4.74107167,
       -0.53620194,  7.15511577])

'remainder'

array([-0.67283537, -0.2458653 , -0.13894765, -0.54084001, -0.74107167,
       -0.53620194,  0.15511577])

'whole_part'

array([-3., -0., -0., -4., -4., -0.,  7.])

In [76]:
# isnan Return boolean array indicating whether each value is NaN (Not a Number)
display(x)
display("np.isnan",np.isnan(x))

array([ 0.29211292, -0.43243851,  1.68077287, -0.12891062,  0.16908463,
       -0.24321828,  0.05365252, -1.25405022])

'np.isnan'

array([False, False, False, False, False, False, False, False])

In [84]:
# isfinite, isinf Return boolean array indicating whether each element is finite (non-inf, non-NaN) or infinite, respectively
display(x)
display("np.isinf",np.isinf(x))
display("np.isnan",np.isfinite(x))


array([ 0.29211292, -0.43243851,  1.68077287, -0.12891062,  0.16908463,
       -0.24321828,  0.05365252, -1.25405022])

'np.isinf'

array([False, False, False, False, False, False, False, False])

'np.isnan'

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [96]:
#cos, cosh, sin, sinh, tan, tanh Regular and hyperbolic trigonometric functions
display(x)
display(np.rint(x))
y = np.rint(x)
display("np.cos",np.cos(y))
display("np.cosh",np.cosh(x))
display("np.sin",np.sin(y))
display("np.sinh",np.sinh(x))

display("np.tan",np.tan(y))
display("np.tanh",np.tanh(x))

array([ 0.29211292, -0.43243851,  1.68077287, -0.12891062,  0.16908463,
       -0.24321828,  0.05365252, -1.25405022])

array([ 0., -0.,  2., -0.,  0., -0.,  0., -1.])

'np.cos'

array([ 1.        ,  1.        , -0.41614684,  1.        ,  1.        ,
        1.        ,  1.        ,  0.54030231])

'np.cosh'

array([1.04296923, 1.09496774, 2.77796721, 1.00832049, 1.0143289 ,
       1.02972366, 1.00143964, 1.89492751])

'np.sin'

array([ 0.        , -0.        ,  0.90929743, -0.        ,  0.        ,
       -0.        ,  0.        , -0.84147098])

'np.sinh'

array([ 0.29628501, -0.44604298,  2.59173722, -0.12926795,  0.16989146,
       -0.24562332,  0.05367827, -1.60958077])

'np.tan'

array([ 0.        , -0.        , -2.18503986, -0.        ,  0.        ,
       -0.        ,  0.        , -1.55740772])

'np.tanh'

array([ 0.28407838, -0.40735719,  0.93296178, -0.12820126,  0.16749149,
       -0.23853323,  0.0536011 , -0.84941549])

In [98]:
#arccos, arccosh, arcsin, arcsinh, arctan, arctanh Inverse trigonometric functions
display("x",x)
display("np.rint",np.rint(x))
y = np.rint(x)
display("np.arccos",np.arccos(y))
display("np.arccosh",np.arccosh(x))
display("np.arcsin",np.arcsin(y))
display("np.arcsinh",np.arcsinh(x))
display("np.arctan",np.arctan(y))
display("np.arctanh",np.arctanh(x))

'x'

array([ 0.29211292, -0.43243851,  1.68077287, -0.12891062,  0.16908463,
       -0.24321828,  0.05365252, -1.25405022])

'np.rint'

array([ 0., -0.,  2., -0.,  0., -0.,  0., -1.])

'np.arccos'

array([1.57079633, 1.57079633,        nan, 1.57079633, 1.57079633,
       1.57079633, 1.57079633, 3.14159265])

'np.arccosh'

array([      nan,       nan, 1.1091227,       nan,       nan,       nan,
             nan,       nan])

'np.arcsin'

array([ 0.        , -0.        ,         nan, -0.        ,  0.        ,
       -0.        ,  0.        , -1.57079633])

'np.arcsinh'

array([ 0.28811045, -0.41998269,  1.29103074, -0.12855622,  0.16828915,
       -0.24088201,  0.05362681, -1.05012067])

'np.arctan'

array([ 0.        , -0.        ,  1.10714872, -0.        ,  0.        ,
       -0.        ,  0.        , -0.78539816])

'np.arctanh'

array([ 0.30087474, -0.46289222,         nan, -0.1296319 ,  0.1707242 ,
       -0.24819191,  0.05370409,         nan])

In [102]:
# logical_not Compute truth value of not x element-wise (equivalent to ~arr).
display("x", x)
np.logical_not(x)

'x'

array([ 0.29211292, -0.43243851,  1.68077287, -0.12891062,  0.16908463,
       -0.24321828,  0.05365252, -1.25405022])

array([False, False, False, False, False, False, False, False])

In [5]:
"""These are referred to as unary ufuncs. Others, such as add or maximum, take two arrays
(thus, binary ufuncs) and return a single array as the result:"""
x = np.random.randn(8)
y = np.random.randn(8)
display("x",x)
display("y",y)
maximam = np.maximum(x, y)
#it compare elements of both array at every index and keep those pne which is greater at particular index in final answer 
display("maximam",maximam)

'x'

array([ 2.47062974, -0.17074931, -1.47770278,  2.00138561,  2.36243895,
       -1.29879203,  0.42612469,  0.97544994])

'y'

array([-1.53934585,  0.58598552, -0.80101747,  0.18252664,  0.26386404,
        0.73780993,  0.37642809, -0.63301872])

'maximam'

array([ 2.47062974,  0.58598552, -0.80101747,  2.00138561,  2.36243895,
        0.73780993,  0.42612469,  0.97544994])

In [6]:
add = np.add(x,y)
display("add",add)

'add'

array([ 0.93128389,  0.41523621, -2.27872025,  2.18391225,  2.62630299,
       -0.56098209,  0.80255278,  0.34243121])

In [16]:
display(arr)

array([-3.67283537, -0.2458653 , -0.13894765, -4.54084001, -4.74107167,
       -0.53620194,  7.15511577])

In [62]:
sqrt = np.sqrt(arr)
display("sqrt",sqrt) # it shows that -ve values sqrt is nan 

'sqrt'

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [63]:
# abs, fabs Compute the absolute value element-wise for integer, „oating-point, or complex values
display("arr",arr)
remove_negative_sign = np.abs(arr)
display("remove_negative_sign np.abs",remove_negative_sign)
remove_negative_sign_fabs = np.fabs(arr)
display("remove_negative_sign np.fabs",remove_negative_sign_fabs)

'arr'

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

'remove_negative_sign np.abs'

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

'remove_negative_sign np.fabs'

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [78]:
display("arr",arr)
remove_negative_sign = np.fabs(arr)
display("remove_negative_sign np.fabs",remove_negative_sign)

'arr'

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

'remove_negative_sign np.fabs'

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [79]:
arr = np.arange(10)
display(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
np.abs(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
np.isfinite(arr)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [112]:
import numpy as np 
 
data=np.arange(1,101,dtype=int) 
for i in range(len(data)): 
    if(i%2==1): 
        data[i]=-1 
    print(data) 
    break
#data

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [118]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
for i in arr:
    if(i%2==1):
        arr[i]=-1
    print(arr)
    break

[0 1 2 3 4 5 6 7 8 9]


In [131]:
import numpy as np

new_array = np.array([12,15,17,18,23,26,45])
#ass =(new_array%2)
#print(ass==0)
out = np.clip(new_array, new_array%2==1, 9)
print("The clipped array:", out)

The clipped array: [9 9 9 9 9 9 9]


In [132]:
#write a email for customer that return the product but could get his money back
import numpy as np

def one_hot_encode(array):
    unique_values = np.unique(array)
    one_hot_encodings = np.eye(len(unique_values))[array]
    return one_hot_encodings

array = np.array([1, 0, 2, 1, 0])
one_hot_encodings = one_hot_encode(array)
print(one_hot_encodings)


[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [4]:
import numpy as np
array = np.array([1, 0, 2, 1, 0])
display(array)
unique_values = np.unique(array)
display(unique_values)
one_hot_encodings = np.eye(len(unique_values))[array]
display(one_hot_encodings)

array([1, 0, 2, 1, 0])

array([0, 1, 2])

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [5]:
import numpy as np

def count_unique_values_row_wise(arr):
    counts = np.empty(arr.shape[0], dtype=int)
    for i, row in enumerate(arr):
        unique_values = set(row)
        count = len(unique_values)
        counts[i] = count
    return counts

np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
print(count_unique_values_row_wise(arr))


[7 7 5 7 7 8]


In [3]:
import numpy as np
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
display(arr)
counts = [np.unique(row, return_counts=True)[1] for row in arr]
counts = np.array([np.bincount(np.unique(row, return_counts=True)[1], minlength=11) for row in arr])[:, 1:]
display(counts)

array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
       [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
       [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
       [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
       [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
       [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])

array([[4, 3, 0, 0, 0, 0, 0, 0, 0, 0],
       [5, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [2, 1, 2, 0, 0, 0, 0, 0, 0, 0],
       [4, 3, 0, 0, 0, 0, 0, 0, 0, 0],
       [4, 3, 0, 0, 0, 0, 0, 0, 0, 0],
       [6, 2, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [14]:
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
display(arr)
for row in arr:
    counts = np.unique(row, return_counts=True)
    #display(counts)
    counts = np.unique(row, return_counts=True)[1]
    #display(counts)
    #return_counts=True tell howmany times a particular element come in list/array and
    #if add [1] so it only bring the which would have quantity of unique element apprence only not array of unique eelements 
    counts = np.array([np.bincount(row)])
    display("you",counts)

array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
       [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
       [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
       [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
       [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
       [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])

'you'

array([[0, 1, 0, 2, 1, 1, 1, 0, 2, 2]], dtype=int64)

'you'

array([[0, 2, 1, 3, 0, 1, 0, 1, 0, 1, 1]], dtype=int64)

'you'

array([[0, 0, 3, 0, 2, 3, 1, 0, 1]], dtype=int64)

'you'

array([[0, 1, 0, 2, 1, 0, 1, 0, 2, 1, 2]], dtype=int64)

'you'

array([[0, 2, 2, 2, 0, 0, 1, 1, 1, 1]], dtype=int64)

'you'

array([[0, 1, 1, 1, 1, 1, 2, 0, 0, 2, 1]], dtype=int64)

In [ ]:
[[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3]
[[0, 1, 0, 2, 1, 1, 1, 0, 2, 2]]
[1, 3, 4, 5, 6, 8, 9]
[1, 2, 1, 1, 1, 2, 2]